version: "3.1"
services:
    app-nginx:
        image: nginx:alpine
        container_name: app-webserver
        volumes:
            - .:/var/www/html
            - ./images/nginx/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5001:80"

    app-php-fpm:
        build: images/php
        container_name: app-php-fpm
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            PHP_IDE_CONFIG: "serverName=docker"

    app-redis:
        image: redis:3.2-alpine
        ports:
            - "6381:6379"

networks:
    default:
        external:
            name: app_default
